-- ============================================================
-- 004_create_orders.sql
-- Orders and order_items for TFI ecommerce
-- ============================================================
-- Design decisions:
--   • order_number uses a human-readable format ORD-YYYYMMDD-XXXXX
--     generated by a trigger + sequence. This is what customers see in
--     WhatsApp messages and on the website.
--   • status enum covers the full Indian ecommerce lifecycle including
--     payment_pending / payment_confirmed / payment_failed states
--     (critical for Razorpay async flows).
--   • total_amount uses NUMERIC(10,2) — never FLOAT — to avoid
--     floating-point rounding on INR currency.
--   • shipping_address is JSONB (snapshot at order time) rather than a FK
--     to an addresses table, because the user might edit/delete their
--     address after placing the order.
--   • product_id in order_items is VARCHAR (not a FK) so the order
--     survives product catalog changes. product_name + unit_price are
--     snapshotted at order time for the same reason.
--   • Soft delete on orders (deleted_at) for compliance / auditing.
-- ============================================================

-- Idempotent teardown
DROP TRIGGER IF EXISTS set_updated_at_orders ON orders;
DROP TRIGGER IF EXISTS set_order_number ON orders;
DROP FUNCTION IF EXISTS generate_order_number() CASCADE;
DROP SEQUENCE IF EXISTS order_number_seq CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TYPE IF EXISTS order_status CASCADE;

-- ============================================================
-- Enum: order lifecycle statuses
-- ============================================================
CREATE TYPE order_status AS ENUM (
  'pending',
  'payment_pending',
  'payment_confirmed',
  'payment_failed',
  'processing',
  'shipped',
  'out_for_delivery',
  'delivered',
  'cancelled'
);

COMMENT ON TYPE order_status IS 'Full Indian ecommerce order lifecycle. Payment states are explicit for Razorpay async webhooks.';

-- ============================================================
-- Sequence for the daily serial portion of order_number
-- ============================================================
CREATE SEQUENCE order_number_seq
  START WITH 1
  INCREMENT BY 1
  NO MAXVALUE
  CACHE 10;

COMMENT ON SEQUENCE order_number_seq IS 'Monotonically increasing serial used in ORD-YYYYMMDD-XXXXX order numbers.';

-- ============================================================
-- Function: generate human-readable order number
-- ============================================================
CREATE OR REPLACE FUNCTION generate_order_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.order_number IS NULL OR NEW.order_number = '' THEN
    NEW.order_number := 'ORD-' ||
                        TO_CHAR(NOW(), 'YYYYMMDD') || '-' ||
                        LPAD(NEXTVAL('order_number_seq')::TEXT, 5, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION generate_order_number()
  IS 'Auto-generates ORD-YYYYMMDD-XXXXX order numbers on INSERT when not provided.';

-- ============================================================
-- Orders table
-- ============================================================
CREATE TABLE orders (
  id               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  user_id          UUID          NOT NULL
                                 REFERENCES users(id)
                                 ON DELETE RESTRICT,  -- never cascade-delete orders

  -- Human-readable order number: ORD-20260521-00042
  order_number     VARCHAR(20)   NOT NULL UNIQUE,

  status           order_status  NOT NULL DEFAULT 'pending',

  -- INR amounts. NUMERIC avoids floating-point rounding.
  total_amount     NUMERIC(10,2) NOT NULL DEFAULT 0,

  currency         VARCHAR(3)    NOT NULL DEFAULT 'INR',

  -- Frozen snapshot of the delivery address at order time.
  shipping_address JSONB,

  -- Extensible metadata (coupon codes, UTM params, etc.).
  metadata         JSONB,

  -- Soft delete for compliance.
  deleted_at       TIMESTAMPTZ,

  created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

  -- Guard: total can't be negative.
  CONSTRAINT chk_total_non_negative CHECK (total_amount >= 0)
);

-- ============================================================
-- Order number auto-generation trigger
-- ============================================================
CREATE TRIGGER set_order_number
  BEFORE INSERT ON orders
  FOR EACH ROW
  EXECUTE FUNCTION generate_order_number();

-- ============================================================
-- Order Items table
-- ============================================================
CREATE TABLE order_items (
  id           UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  order_id     UUID          NOT NULL
                              REFERENCES orders(id)
                              ON DELETE CASCADE,

  -- VARCHAR, NOT a FK — product catalog may change after the order.
  product_id   VARCHAR(100)  NOT NULL,

  -- Snapshot of the product name at purchase time.
  product_name VARCHAR(255)  NOT NULL,

  quantity     INT           NOT NULL,

  -- Snapshot of the unit price at purchase time.
  unit_price   NUMERIC(10,2) NOT NULL,

  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

  -- Guards
  CONSTRAINT chk_quantity_positive CHECK (quantity > 0),
  CONSTRAINT chk_unit_price_non_negative CHECK (unit_price >= 0)
);

-- ============================================================
-- Indexes
-- ============================================================
-- Hot path: "my orders" screen.
CREATE INDEX idx_orders_user_id
  ON orders (user_id, created_at DESC)
  WHERE deleted_at IS NULL;

-- Admin dashboard: filter by status.
CREATE INDEX idx_orders_status
  ON orders (status)
  WHERE deleted_at IS NULL;

-- Order detail page: fetch items for an order.
CREATE INDEX idx_order_items_order_id
  ON order_items (order_id);

-- Analytics: search by product across orders.
CREATE INDEX idx_order_items_product_id
  ON order_items (product_id);

-- ============================================================
-- Auto-update trigger (orders only; order_items are immutable)
-- ============================================================
CREATE TRIGGER set_updated_at_orders
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION trigger_set_updated_at();

-- ============================================================
-- Table & column comments
-- ============================================================
COMMENT ON TABLE orders IS 'Customer orders. Soft-deletable. order_number is the human-visible ID.';
COMMENT ON COLUMN orders.order_number IS 'Human-readable: ORD-YYYYMMDD-XXXXX. Auto-generated by trigger.';
COMMENT ON COLUMN orders.shipping_address IS 'JSONB snapshot of address at order time. Survives address edits.';
COMMENT ON COLUMN orders.total_amount IS 'NUMERIC(10,2) to avoid float rounding on INR.';

COMMENT ON TABLE order_items IS 'Line items in an order. Product data is snapshotted (not FK-referenced).';
COMMENT ON COLUMN order_items.product_id IS 'Catalog product ID (VARCHAR). Not a FK so orders survive product deletion.';
COMMENT ON COLUMN order_items.product_name IS 'Product name snapshot at purchase time.';
COMMENT ON COLUMN order_items.unit_price IS 'Price snapshot at purchase time.';
